### ISSUE TITLE
Only show output ts-node and typescript version on start if `--debug` is enabled

### ISSUE THREAD

**Issue by twick00** [wclr/ts-node-dev#129]
I want to use `ts-node-dev` to test a cli render engine but it outputs unnecessary text to the console:
`Using ts-node version 8.6.2, typescript version 3.7.5`

Can we wrap this with `log.debug` instead of `console.log`?
https://github.com/whitecolor/ts-node-dev/blob/master/lib/index.js#L76

If not this, can we at least add a `--quiet` flag to reduce output?

**Comment by whitecolor** [comment]
Will see.

**Comment by DarkLite1** [comment]
Related to #136

**Comment by plashenkov** [comment]
I second this. Why do I have to know my ts-node version and typescript version **on each** restart (honestly I even do not need them at all since I can `npx ts-node --version` and `npx tsc --version` when I really need them)? We all already have too much noise in our consoles. Please add `--silent` or `--quiet` for us and make our life a little less noisy :)

P.S. Thanks for the project! It's great!

**Comment by twick00** [comment]
Seems like this is no longer an issue with the addition of the `--quiet` flag. 
Thanks @wclr!
