### ISSUE TITLE
hot-reloading with Docker bind mounts

### ISSUE THREAD

**Issue by bahtou** [wclr/ts-node-dev#240]
## Issue description
Trying to enable hot-reloading with Docker using ts-node-dev. The following is my setup:

`tsconfig.json`

```json
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": false,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "inlineSources": true,
    "outDir": "build"
  },
  "include": ["src/**/*"]
}
```

In my `package.json` I have set

`"start": "ts-node-dev --files --transpile-only --watch src -- src/bin/www",`

Once I build the image I run a container with:

`docker run --name hot-reload -v $PWD/src:/app/src -p 3000:3000 -d hot-reload`

I modify files but the `ts-node-dev` doesn't seem to pick up the local file changes. If I `exec` into the container I see that the file changes have propagated into the container.

Any ideas on how to get hot-reloading with `ts-node-dev` in a docker environment?

## Context

*OS version (is it docker or host?), ts-node-dev version*
Docker               - 19.03.12
ts-node-dev      - 1.1.1

**Comment by bahtou** [comment]
Doing some research on this. Is there an equivalent of `Chokidar's polling` similar to nodemon?

>In some networked environments (such as a container running nodemon reading across a mounted drive), you will need to use the legacyWatch: true which enables Chokidar's polling. 
>Via the CLI, use either --legacy-watch or -L for short:
> `nodemon -L`
> Though this should be a last resort as it will poll every file it can find.

https://github.com/remy/nodemon#application-isnt-restarting

**Comment by wclr** [comment]
Use `--poll` flag.

**Comment by uncvrd** [comment]
Would this be a docker constraint I should be prepared to deal with? I've been delving in to this code and `chokidar` to see if I can pinpoint why it doesn't update....

I'm trying to use Skaffold for kubernetes to develop locally. There's a feature called `File Sync` that basically volume mounts and propagates local changes to the Docker container running in minikube. I feel like there is some sort of race condition because just like OP, when I `exec` in to my container, I see the updated file but `ts-node-dev` restart....sometimes. 

Frustratingly, there is no consistency. Sometimes it live reloads 2-3 times perfectly and sometimes it doesn't work the first time I spin up a dev server with live-reload.

Any alternative suggestions out there besides polling to try and use?
